basic:
    name: 'Recademics monitoring'
    breakpoints:
        - 390
        - 1920
    pages:
        - 'https://recademics.com'
        - 'https://recademics.com/boating'
        - 'https://recademics.com/hunting'
        - 'https://recademics.com/hunting/nevada'
        - 'https://recademics.com/boating/texas'
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/Kiev
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
