basic:
    name: 'Recademics monitoring'
    breakpoints:
        - 390
        - 1920
    pages:
        - 'https://recademics.com'
        - 'https://recademics.com/hunting'
        - 'https://recademics.com/hunting/nevada'
        - 'https://recademics.com/boating/texas'
        - 'https://recademics.com/boating'
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/Kiev
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ".elementor-widget-slider_revolution\n.e-n-carousel.swiper\n.swiper-pagination"
    remove: .elementor-background-video-container
    delay: 60
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ".menu-item .elementor-item:after {\n\tbackground-color: transparent !important;\n}"
    mock_content: {  }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
